name: Tests

on:
  push:
    branches: [ main, develop, ci/add-github-actions-tests ]
  pull_request:
    branches: [ main, develop, ci/add-github-actions-tests ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.3, 8.4, 8.5]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, openssl, json
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-suggest

      - name: Run tests
        run: composer test